function temple_abm_mexican_wave
%TEMPLE_ABM_MEXICAN_WAVE
%   Model for a mexican wave in a sports stadium, generated by
%   spectators who stand up and sit down to create the wave as
%   an emergent structure. The provided model is very simple
%   and should be improved. Model: 0=sitting; 1=standing.
%   Update rule: if sitting and left neighbor standing, then
%   stand up; if standing, then sit down.
%
% 01/2016 by Benjamin Seibold
%            http://www.math.temple.edu/~seibold/


% HW 1 - by Dean Quach
%part c


% Parameters
n = 60; % number of agents

% Initialization
x =[1:n==round(1)]; % one agent from the left stands up

% Computation
for j = 1:40 % time loop, 40 for now
    % Plotting
    fprintf('%d',x)

    fprintf('\n')
    % Update rule
    x = ~x&x([end 1:end-1]);
   % y = ~y&y([end 1:end-1]);
    pause
end



