function temple_abm_mexican_wave
%TEMPLE_ABM_MEXICAN_WAVE
%   Model for a mexican wave in a sports stadium, generated by
%   spectators who stand up and sit down to create the wave as
%   an emergent structure. The provided model is very simple
%   and should be improved. Model: 0=sitting; 1=standing.
%   Update rule: if sitting and left neighbor standing, then
%   stand up; if standing, then sit down.
%
% 01/2016 by Benjamin Seibold
%            http://www.math.temple.edu/~seibold/


% HW 1 - by Dean Quach
% Either make out of the 5 standing up some sit down some stand up on each 
% loop, simulating if somone sits down too ealry and changes their mind or
% something.

% Or I should do probability that the next person may not stand.


% Parameters
n = 40; % number of agents

% Initialization
x = [1:n==round(n/3)]; % one agent from the left stands up

% Computation
for j = 1:40 % time loop
    % Plotting
    fprintf('%d',x) %plotting both row vectors side by side/one after another. i.e.[x y]
    fprintf('\n')
    % Update rule
    x = ~x&x([end 1:end-1]); % indices of possible contagion from left
    x = ~x&x([end 1:end-1]);
    pause
end


% In this case, the waves colide and I assume it to die off, or possibly
% the person on the other side of the middle person doesn't want to have to
% stand up that quickly .

